# A first workflow to play around with the editor

name: My First Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name: Greet the user
        run: |
          echo "Hello ${{ vars.WHO_TO_GREET}} from ${{ github.actor}}"
          echo "My secret is ${{secrets.MY_SECRET}}"
          echo "Current branch is ${{ github.ref}}"
        shell: bash
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - run: tree
  Test:
    runs-on: ubuntu-latest
    environment: Test
    needs: first_job
    steps:
      - run: |
          sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
          echo "Hello ${{ vars.WHO_TO_GREET}} from ${{ github.actor}}"
          echo "My secret is '$sec'"
  Load-Test:
    runs-on: ubuntu-latest
    environment: Load-test
    needs: first_job
    steps:
      - run: |
          sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
          echo "Hello ${{ vars.WHO_TO_GREET}} from ${{ github.actor}}"
          echo "Sleeping"
          sleep(5)
          echo "Finished sleeping"
          echo "My secret is '$sec'"    
  Production:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://writeabout.net
    needs: [Test, Load-Test]
    steps:
    - run: |
        sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
        echo "Hello ${{ vars.WHO_TO_GREET}} from ${{ github.actor}}"
        echo "My secret is '$sec'"  
  
          
